# Generated by Django 2.2.3 on 2019-07-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_status',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=False),
        ),
    ]
